linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - misspell
    - unconvert
    
linters-settings:
  errcheck:
    check-blank: true
  
run:
  timeout: 5m
  skip-dirs:
    - vendor

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
